### ISSUE TITLE
Error building with gulp + browserify + babel

### ISSUE THREAD

**Issue by exos** [ocombe/angular-localForage#115]
I have this error when i tried to browserify my app:

```
ReferenceError: [BABEL] /home/exos/projectv/node_modules/localforage/dist/localforage.js: Using removed Babel 5 option: /home/exos/projectv/node_modules/localforage/.babelrc.loose - Specify the `loose` option for the relevant plugin you are using or use a preset that sets the option.
    at Logger.error (/home/exos/projectv/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/home/exos/projectv/node_modules/babel-core/lib/transformation/file/options/option-manager.js:288:20)
    at OptionManager.addConfig (/home/exos/projectv/node_modules/babel-core/lib/transformation/file/options/option-manager.js:232:10)
    at OptionManager.findConfigs (/home/exos/projectv/node_modules/babel-core/lib/transformation/file/options/option-manager.js:436:16)
    at OptionManager.init (/home/exos/projectv/node_modules/babel-core/lib/transformation/file/options/option-manager.js:484:12)
    at File.initOptions (/home/exos/projectv/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/home/exos/projectv/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/home/exos/projectv/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at Babelify._flush (/home/exos/projectv/node_modules/babelify/index.js:27:24)
    at Babelify.<anonymous> (_stream_transform.js:118:12)
```

I install all babel plugins there are on the localForage package.json:

My package.json section:
```
  "devDependencies": {
    "angular-localforage": "^1.2.5",
    "babel-plugin-add-module-exports": "^0.2.1",
    "babel-plugin-system-import-transformer": "^2.0.0",
    "babel-plugin-transform-es2015-modules-umd": "^6.8.0",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-es2015-loose": "^7.0.0",
    "babelify": "^7.3.0",
    "brfs-htmlmin": "^2.0.0",
    "gulp": "^3.9.1",
    "gulp-browserify": "^0.5.1",
    "gulp-jshint": "^2.0.1",
    "gulp-rename": "^1.2.2",
    "gulp-sass": "^2.3.1",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-uglify": "^1.5.3",
    "ionic-material": "https://github.com/zachfitz/Ionic-Material.git#v0.4.2",
    "jshint": "^2.9.2",
    "jshint-stylish": "^2.2.0",
    "napa": "^2.3.0",
    "yargs": "^4.7.1"
 }
```

My gulp task:
```
gulp.task('build-lib', function () {

    var options = {
        insertGlobals : true,
        debug : argv.debug,
        shim: {
            angular: {
                path: "./node_modules/ionic/release/js/ionic.bundle.min.js",
                exports: "angular"
            }
        },
        extensions: [
            'es6'
        ],
        transform: [
            'babelify',
            'brfs-htmlmin'
        ]
    };

    return gulp.src(paths.lib)
        .pipe(sourcemaps.init())
        .pipe(browserify(options))
        .pipe(sourcemaps.write())
        .pipe(rename('app.js'))
        //.pipe(uglify())
        .pipe(rename('app.js'))
        .pipe(gulp.dest('www/js'));
});

```

my .babelrc
```
{
    "presets": ["es2015-loose"],
    "plugins": [
        "add-module-exports"
    ]
}
```

And I copied the file .babelrc-umd from the project. But I get the same error.

Some versions:
```
node: v5.11.1
npm: 3.8.6
```

**Comment by scotttrinh** [comment]
I'm not super familiar with Babel: what do you make of the first line of your error message:

```
ReferenceError: [BABEL] /home/exos/projectv/node_modules/localforage/dist/localforage.js: Using removed Babel 5 option: /home/exos/projectv/node_modules/localforage/.babelrc.loose - Specify the `loose` option for the relevant plugin you are using or use a preset that sets the option.
```

?

Looks like an issue with localForage? I don't see any reference to `.babelrc.loose` in their code, but I'll dig a bit.

**Comment by exos** [comment]
Yes, i'ts, I re-post it in https://github.com/mozilla/localForage/issues/578

**Comment by scotttrinh** [comment]
@exos I see that we just need to package a release that bumps the localForage to 1.4. I just took over the maintenance of this package, so this weekend, I'm going to put together a roadmap and keeping up with the upstream library is going to be high priority for me. I'm going to reopen this issue until the new version is out.

**Comment by exos** [comment]
Yes, I continued this issue on the localForage repo's ([this is the issue](https://github.com/mozilla/localForage/issues/578#issuecomment-226010958)) and I got to a solution instaling first the last version (1.4) of localForage, or installing this package but using the master branch instead of the published release.
